# Generated by Django 4.1.6 on 2023-02-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('timetocomplete', models.PositiveIntegerField(blank=True, null=True)),
                ('payment', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Job/Images')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('applied_by', models.ManyToManyField(to='userapp.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.service')),
                ('skill', models.ManyToManyField(to='userapp.skill')),
            ],
        ),
    ]
