# Generated by Django 4.1.6 on 2023-02-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_job_applied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, to='userapp.profile'),
        ),
    ]
