# Generated by Django 4.1.6 on 2023-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_service_created_on_service_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
