# Generated by Django 4.1.6 on 2023-03-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_service_created_on_alter_service_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_by',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profile')),
                ('applied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.job')),
            ],
        ),
    ]
