# Generated by Django 4.1.6 on 2023-03-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_job_applied_by_job_requirements_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_profile', to='userapp.profile'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_job', to='userapp.job'),
        ),
    ]
