# Generated by Django 4.1.6 on 2023-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_status_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
