# Generated by Django 4.1.6 on 2023-03-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_status_created_on_status_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='active', max_length=20),
        ),
    ]
