# Generated by Django 4.1.6 on 2023-03-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_job_completed_by_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='completed_by',
            new_name='assigned_to',
        ),
    ]
