# Generated by Django 4.1.6 on 2023-03-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_review_job_alter_review_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inprogress', 'inprogress'), ('not completed', 'not completed'), ('completed', 'completed')], max_length=20, null=True),
        ),
    ]
