# Generated by Django 4.1.6 on 2023-03-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inprogress', 'inprogress'), ('not completed', 'not completed'), ('completed', 'completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.status'),
        ),
    ]
